// Mock campaign data
export const mockCampaignData = {
  id: 'camp-001',
  name: 'Magicfit Summer 2026 Influencer Campaign',
  brand_name: 'Magicfit',
  description: 'Summer fitness campaign featuring top creators across Instagram, TikTok, and YouTube',
  budget: 50000,
  start_date: '2026-05-01',
  end_date: '2026-08-31',
};

// Mock creators data
export const mockCreators = [
  {
    id: 'creator-001',
    campaign_id: 'camp-001',
    creator_name: '@fitness_sarah',
    platform: 'Instagram',
    deliverable: '1x Dedicated Reel (60s)',
    approval_status: 'Published',
    progress_score: 100,
    live_date: '2026-05-15',
    video_link: 'https://instagram.com/fitness_sarah/reels/001',
    published_video_link: 'https://instagram.com/fitness_sarah/reels/001',
    views: 125000,
    engagement_rate: 8.5,
    spend: 5000,
  },
  {
    id: 'creator-002',
    campaign_id: 'camp-001',
    creator_name: '@tiktok_trainer_mike',
    platform: 'TikTok',
    deliverable: '2x TikTok Videos (15s + 30s)',
    approval_status: 'Video Pending Approval',
    progress_score: 75,
    live_date: '2026-05-20',
    video_link: 'https://tiktok.com/@tiktok_trainer_mike/video/12345',
    published_video_link: null,
    views: 0,
    engagement_rate: 0,
    spend: 4000,
  },
  {
    id: 'creator-003',
    campaign_id: 'camp-001',
    creator_name: '@youtube_fitness_pro',
    platform: 'YouTube',
    deliverable: '1x YouTube Short (60s)',
    approval_status: 'Script Sent',
    progress_score: 40,
    live_date: '2026-06-01',
    video_link: null,
    published_video_link: null,
    views: 0,
    engagement_rate: 0,
    spend: 6000,
  },
  {
    id: 'creator-004',
    campaign_id: 'camp-001',
    creator_name: '@gym_anna',
    platform: 'Instagram',
    deliverable: '1x Carousel Post + 1x Reel',
    approval_status: 'Revisions Requested',
    progress_score: 60,
    live_date: '2026-05-25',
    video_link: 'https://instagram.com/gym_anna/reels/draft-001',
    published_video_link: null,
    views: 0,
    engagement_rate: 0,
    spend: 4500,
  },
  {
    id: 'creator-005',
    campaign_id: 'camp-001',
    creator_name: '@fit_david_vlogs',
    platform: 'YouTube',
    deliverable: '1x Long-form Video (5 min)',
    approval_status: 'Approved',
    progress_score: 85,
    live_date: '2026-06-10',
    video_link: null,
    published_video_link: null,
    views: 0,
    engagement_rate: 0,
    spend: 7000,
  },
  {
    id: 'creator-006',
    campaign_id: 'camp-001',
    creator_name: '@tiktok_emma_fit',
    platform: 'TikTok',
    deliverable: '3x TikTok Videos (15-30s)',
    approval_status: 'Ideation',
    progress_score: 20,
    live_date: '2026-06-15',
    video_link: null,
    published_video_link: null,
    views: 0,
    engagement_rate: 0,
    spend: 3500,
  },
  {
    id: 'creator-007',
    campaign_id: 'camp-001',
    creator_name: '@instagram_coach_james',
    platform: 'Instagram',
    deliverable: '1x Reel + 1x Story Series',
    approval_status: 'Published',
    progress_score: 100,
    live_date: '2026-05-22',
    video_link: 'https://instagram.com/instagram_coach_james/reels/002',
    published_video_link: 'https://instagram.com/instagram_coach_james/reels/002',
    views: 89000,
    engagement_rate: 7.2,
    spend: 5500,
  },
  {
    id: 'creator-008',
    campaign_id: 'camp-001',
    creator_name: '@youtube_shorts_tyler',
    platform: 'YouTube',
    deliverable: '2x YouTube Shorts (60s)',
    approval_status: 'Video Pending Approval',
    progress_score: 70,
    live_date: '2026-06-05',
    video_link: 'https://youtube.com/shorts/draft-001',
    published_video_link: null,
    views: 0,
    engagement_rate: 0,
    spend: 4800,
  },
];

// Mock notes for creators
export const creatorNotes: Record<string, any[]> = {
  'creator-001': [
    {
      id: 'note-001',
      creator_id: 'creator-001',
      author_id: 'client-user-id',
      author_name: 'Marketing Manager',
      author_role: 'client',
      content: 'Excellent work! The branding is perfect and the content is very engaging.',
      is_internal: false,
      created_at: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    },
    {
      id: 'note-002',
      creator_id: 'creator-001',
      author_id: 'editor-user-id',
      author_name: 'Campaign Manager',
      author_role: 'editor',
      content: 'Published successfully on May 15th. Already hitting great engagement numbers!',
      is_internal: false,
      created_at: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    },
  ],
  'creator-002': [
    {
      id: 'note-003',
      creator_id: 'creator-002',
      author_id: 'editor-user-id',
      author_name: 'Campaign Manager',
      author_role: 'editor',
      content: 'Video is ready for client review. Waiting on approval to publish.',
      is_internal: false,
      created_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    },
    {
      id: 'note-004',
      creator_id: 'creator-002',
      author_id: 'editor-user-id',
      author_name: 'Campaign Manager',
      author_role: 'editor',
      content: 'Creator is very responsive and responsive to notes. No issues so far.',
      is_internal: true,
      created_at: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    },
  ],
  'creator-004': [
    {
      id: 'note-005',
      creator_id: 'creator-004',
      author_id: 'client-user-id',
      author_name: 'Marketing Manager',
      author_role: 'client',
      content: 'The reel looks good overall, but can we increase the Magicfit logo visibility in the final scene? It feels a bit subtle.',
      is_internal: false,
      created_at: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
    },
    {
      id: 'note-006',
      creator_id: 'creator-004',
      author_id: 'editor-user-id',
      author_name: 'Campaign Manager',
      author_role: 'editor',
      content: 'Made the requested changes to increase logo visibility. Sent revised draft to creator for final touches.',
      is_internal: false,
      created_at: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    },
    {
      id: 'note-007',
      creator_id: 'creator-004',
      author_id: 'editor-user-id',
      author_name: 'Campaign Manager',
      author_role: 'editor',
      content: 'Creator is implementing changes. Should have updated draft by tomorrow.',
      is_internal: true,
      created_at: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    },
  ],
};

// Mock notes for a specific creator
export const getMockNotes = (creatorId: string) => {
  return creatorNotes[creatorId] || [];
};


